#!/usr/bin/env tsx
/**
 * Stage 4: Generate AI analysis report for the tool
 */

import { callLlm } from "../lib/llm";
import type { EnrichedTool } from "./enrich-tool";

export interface ToolReport {
  slug: string;
  title: string;
  summary: string;
  scores: {
    features: number;
    pricing: number;
    easeOfUse: number;
    documentation: number;
    community: number;
    overall: number;
  };
  pros: string[];
  cons: string[];
  verdict: string;
  markdown: string;
}

const SYSTEM_PROMPT = `You are a senior software analyst. Generate a comprehensive analysis report for the given tool.

Rules:
- ONLY use the data provided. NEVER invent features, pricing, or statistics.
- If data is insufficient, say "Not enough data to assess" for that dimension.
- Be specific and factual. Reference actual features and pricing from the data.
- Scores should be 1-10 based on the available evidence.
- Pros and cons must be grounded in the provided data.

Output JSON format:
{
  "summary": "2-3 sentence executive summary",
  "scores": {
    "features": 8,
    "pricing": 7,
    "easeOfUse": 9,
    "documentation": 6,
    "community": 5,
    "overall": 7
  },
  "pros": ["pro1", "pro2", "pro3"],
  "cons": ["con1", "con2", "con3"],
  "verdict": "Final recommendation paragraph"
}`;

export async function generateToolReport(tool: EnrichedTool): Promise<ToolReport> {
  const userPrompt = `Analyze this software tool and generate a report:

Name: ${tool.name}
Tagline: ${tool.tagline}
Description: ${tool.description}
Category: ${tool.category}
Website: ${tool.websiteUrl}
Open Source: ${tool.openSource}
GitHub Stars: ${tool.githubStars ?? "N/A"}
Features: ${tool.features.join(", ")}
Pricing: ${JSON.stringify(tool.pricing)}
Integrations: ${tool.integrations.join(", ") || "N/A"}
Target Audience: ${tool.targetAudience}

Generate the analysis report in JSON format.`;

  const response = await callLlm(SYSTEM_PROMPT, userPrompt);
  const data = JSON.parse(response.content);

  const title = `${tool.name} Review: Features, Pricing & Analysis`;

  const markdown = `---
title: "${title}"
date: "${new Date().toISOString().split("T")[0]}"
tool: "${tool.slug}"
type: "report"
---

# ${title}

${data.summary}

## Scores

| Dimension | Score |
|-----------|-------|
| Features | ${data.scores?.features ?? "N/A"}/10 |
| Pricing | ${data.scores?.pricing ?? "N/A"}/10 |
| Ease of Use | ${data.scores?.easeOfUse ?? "N/A"}/10 |
| Documentation | ${data.scores?.documentation ?? "N/A"}/10 |
| Community | ${data.scores?.community ?? "N/A"}/10 |
| **Overall** | **${data.scores?.overall ?? "N/A"}/10** |

## Pros

${(data.pros || []).map((p: string) => `- ${p}`).join("\n")}

## Cons

${(data.cons || []).map((c: string) => `- ${c}`).join("\n")}

## Verdict

${data.verdict || "Insufficient data for a recommendation."}

## Tool Info

- **Website**: [${tool.websiteUrl}](${tool.websiteUrl})
${tool.githubUrl ? `- **GitHub**: [${tool.githubUrl}](${tool.githubUrl}) (${tool.githubStars?.toLocaleString() ?? "N/A"} stars)` : ""}
- **Category**: ${tool.category}
- **Open Source**: ${tool.openSource ? "Yes" : "No"}

---
*This report was generated by ToolAlts AI analysis pipeline.*
`;

  return {
    slug: tool.slug,
    title,
    summary: data.summary || "",
    scores: data.scores || { features: 0, pricing: 0, easeOfUse: 0, documentation: 0, community: 0, overall: 0 },
    pros: data.pros || [],
    cons: data.cons || [],
    verdict: data.verdict || "",
    markdown,
  };
}
